site_name: Յանա Նազարյան - ՖաբԴպրոց
site_description: Նախագծային ուսումնառության փաստաթղթավորման կայք Յանա Նազարյանի համար
site_author: Յանա Նազարյան
copyright: Հեղինակային իրավունք 2026 Յանա Նազարյան - Creative Commons Attribution Non Commercial

site_url: https://yananazaryan26-crypto.github.io/fab-academy-site/

extra:
  # Set your own social media below (or remove)
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/fabacademany
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/fabacademany
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/fabacademany
    - icon: fontawesome/brands/linkedin
      link: "https://linkedin.com/in/academany"

theme:
  name: material
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: deep
    accent: indigo
  font:
    # See available fonts at https://fonts.google.com/
    text: Ubuntu
    code: Ubuntu Mono
  icon:
    logo: material/school
  favicon: images/favicon.svg
  features:
    - navigation.tabs
    - navigation.instant

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      # Read more: https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/options/#enabled
      enabled: !ENV [ENABLED_GIT_REVISION_DATE, False]

markdown_extensions:
  - extra
  - smarty
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

nav:
  - Բարի գալուստ իմ էջ: index.md
  - Իմ մասին: about.md
  - Հանձնարարություններ: 
      - "Շաբաթ 1": assignments/week01.md
      - "Շաբաթ 2": assignments/week02.md
      - "Շաբաթ 3": assignments/week03.md
      - "Շաբաթ 4": assignments/week04.md
      - "Շաբաթ 5": assignments/week05.md
      - "Շաբաթ 6": assignments/week06.md
      - "Շաբաթ 7": assignments/week07.md
      - "Շաբաթ 8": assignments/week08.md
      - "Շաբաթ 9": assignments/week09.md
      - "Շաբաթ 10": assignments/week10.md
      - "Շաբաթ 11": assignments/week11.md
      - "Շաբաթ 12": assignments/week12.md
  
  - Նախագծեր: projects/final-project.md
